services:
  - type: web
    name: sachin-portfolio
    env: python
    plan: free        # upgrade later if needed
    buildCommand:
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --no-input
    startCommand: gunicorn Portfolio.wsgi:application --log-file -
    branch: main
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: SECRET_KEY           # add in Render UI (keep value hidden!)
        sync: false
      - key: DATABASE_URL         # autoâ€‘generated when you add a DB
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
